### PR TITLE
change in Floating stats component

### PR DESCRIPTION
**Pull request by Mohammad-dn**

### CODE REVIEW

**Comment by mahdi-eth** [comment]
Hi, We need this request to be merged soon, the changes that have been made in this request is critical for the logic of my page, thank you. @mtabatabaeifard

**Comment by mtabatabaeifard** [comment]
> Hi, We need this request to be merged soon, the changes that have been made in this request is critical for the logic of my page, thank you. @mtabatabaeifard

Hi , please update your code and re-request.
thanks

**Review by mtabatabaeifard — CHANGES_REQUESTED** [review]
Hi , please update your code and re-request.
thanks

**Review by mtabatabaeifard — APPROVED** [review]
Hi , I tested and reviewed your code.
it's able to merge!

**Pull request merged**
