### PR TITLE
structure issues fixed

### PR DESCRIPTION
**Pull request by Honarpishefard**
pages starting with capital letter *fixed*
removed App.css and index.css (instead using assets>styles>global>index.css)
local font added
+ structure improvements

### CODE REVIEW

**Review by mtabatabaeifard — CHANGES_REQUESTED** [review]
Hi, please update your code with master and re-request.
thanks

**Comment by Honarpishefard** [comment]
updated with master

**Review by mtabatabaeifard — CHANGES_REQUESTED** [review]
Hi, I checked your code
Some changes were made to the master branch
Please retrieve and update your code from Master and request again.
Thanks

**Review by mtabatabaeifard — APPROVED** [review]
Hi , I tested and reviewed your code.
it's able to merge!

**Pull request merged**
