### PR TITLE
Created the structure of song page, Is it okay to merge? 

### PR DESCRIPTION
**Pull request by mahdi-eth**

### CODE REVIEW

**Comment by mtabatabaeifard** [comment]
No, it has conflicts.

**Comment by mtabatabaeifard** [comment]
1 more conflict available at src/routes/index.jsx
please add your routes after default routes.
thanks

**Review by mtabatabaeifard — APPROVED** [review]

**Review by mtabatabaeifard — CHANGES_REQUESTED** [review]
Another problem:
Please use the correct folder structure.
The components must be in the shared folder.

**Comment by mahdi-eth** [comment]
It does not have any conflicts.

**Review by mtabatabaeifard — APPROVED** [review]
It's OK To Merge

**Pull request merged**
