### PR TITLE
minor changes

### PR DESCRIPTION
**Pull request by Honarpishefard**

### CODE REVIEW

**Review by mtabatabaeifard — CHANGES_REQUESTED** [review]
Hi , I reviewed your code .
Please Update your codes with latest version of master and re-request.
thanks

**Review by mtabatabaeifard — APPROVED** [review]

**Review by mtabatabaeifard — CHANGES_REQUESTED** [review]
Hi , I reviewed your code again and compared it with master.
please update your code with latest version of master and re-request.
thanks

**Comment by Honarpishefard** [comment]
it says I'm already up to date with master

**Review by mtabatabaeifard — CHANGES_REQUESTED** [review]
Hi , maybe it's a git issue .
please wait until master branch updates again and update your code with that version and re-request.
thanks

**Comment by mtabatabaeifard** [comment]
now , master is updated.
please update your codes and re-request.
thanks

**Comment by mtabatabaeifard** [comment]
now you can merge your codes with master.
just update your code & re-request.
thanks

**Review by mtabatabaeifard — CHANGES_REQUESTED** [review]
Hi , I updated your code with latest version of master.
now it has some conflicts.
please resolve them and re-request.
thanks.

**Review by mtabatabaeifard — APPROVED** [review]
Hi , I tested and reviewed your code.
It's able to merge!

**Pull request merged**
