### PR TITLE
adding the first two pages

### PR DESCRIPTION
**Pull request by Honarpishefard**

### CODE REVIEW

**Review by mtabatabaeifard — CHANGES_REQUESTED** [review]
commit rejected ! please don't touch base url & project structure.

**Comment by Honarpishefard** [comment]
I'm only changing font family and removed container from structure because some pages don't need one so it could be used only in pages that do need it

**Comment by Honarpishefard** [comment]
Screenshot 2022-12-22 165119
this is what it looks like with container

**Review by mtabatabaeifard — APPROVED** [review]

**Comment by mtabatabaeifard** [comment]
Hi , It's OK To Merge!

**Comment by mtabatabaeifard** [comment]
> I'm only changing font family and removed container from structure because some pages don't need one so it could be used only in pages that do need it

It's OK.

**Pull request merged**
